[2023-10-11T05:00:13.141+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker.virtualenv_python manual__2023-10-11T05:00:10.849316+00:00 [queued]>
[2023-10-11T05:00:13.145+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker.virtualenv_python manual__2023-10-11T05:00:10.849316+00:00 [queued]>
[2023-10-11T05:00:13.145+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-11T05:00:13.152+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): virtualenv_python> on 2023-10-11 05:00:10.849316+00:00
[2023-10-11T05:00:13.157+0000] {standard_task_runner.py:57} INFO - Started process 495 to run task
[2023-10-11T05:00:13.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'docker', 'virtualenv_python', 'manual__2023-10-11T05:00:10.849316+00:00', '--job-id', '1426', '--raw', '--subdir', 'DAGS_FOLDER/docker.py', '--cfg-path', '/tmp/tmp_2aag7zx']
[2023-10-11T05:00:13.160+0000] {standard_task_runner.py:85} INFO - Job 1426: Subtask virtualenv_python
[2023-10-11T05:00:13.187+0000] {task_command.py:415} INFO - Running <TaskInstance: docker.virtualenv_python manual__2023-10-11T05:00:10.849316+00:00 [running]> on host 806ac90253f5
[2023-10-11T05:00:13.231+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker' AIRFLOW_CTX_TASK_ID='virtualenv_python' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T05:00:10.849316+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T05:00:10.849316+00:00'
[2023-10-11T05:00:13.232+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv4luzmjjv
[2023-10-11T05:00:13.245+0000] {process_utils.py:186} INFO - Output:
[2023-10-11T05:00:14.025+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 273ms
[2023-10-11T05:00:14.025+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv4luzmjjv, clear=False, no_vcs_ignore=False, global=False)
[2023-10-11T05:00:14.025+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpp3ztp4kz)
[2023-10-11T05:00:14.026+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
[2023-10-11T05:00:14.026+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-10-11T05:00:14.045+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv4luzmjjv/bin/pip install -r /tmp/venv4luzmjjv/requirements.txt
[2023-10-11T05:00:14.056+0000] {process_utils.py:186} INFO - Output:
[2023-10-11T05:00:14.851+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2023-10-11T05:00:15.065+0000] {process_utils.py:190} INFO - Collecting lightgbm==4.1.0 (from -r /tmp/venv4luzmjjv/requirements.txt (line 1))
[2023-10-11T05:00:15.066+0000] {process_utils.py:190} INFO -   Obtaining dependency information for lightgbm==4.1.0 from https://files.pythonhosted.org/packages/b8/9d/1ce80cee7c5ef60f2fcc7e9fa97f29f7a8de3dc5a08922b3b2f1e9106481/lightgbm-4.1.0-py3-none-manylinux_2_28_x86_64.whl.metadata
[2023-10-11T05:00:15.254+0000] {process_utils.py:190} INFO -   Downloading lightgbm-4.1.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
[2023-10-11T05:00:15.539+0000] {process_utils.py:190} INFO - Collecting pandas==2.0.3 (from -r /tmp/venv4luzmjjv/requirements.txt (line 2))
[2023-10-11T05:00:15.539+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pandas==2.0.3 from https://files.pythonhosted.org/packages/f8/7f/5b047effafbdd34e52c9e2d7e44f729a0655efafb22198c45cf692cdc157/pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
[2023-10-11T05:00:15.586+0000] {process_utils.py:190} INFO -   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2023-10-11T05:00:15.757+0000] {process_utils.py:190} INFO - Collecting scikit-learn==1.3.1 (from -r /tmp/venv4luzmjjv/requirements.txt (line 3))
[2023-10-11T05:00:15.758+0000] {process_utils.py:190} INFO -   Obtaining dependency information for scikit-learn==1.3.1 from https://files.pythonhosted.org/packages/91/4e/752fd6e0b6b828a9cd815941fb70723eaef5d0f4efd8b9b0eee7864b3511/scikit_learn-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
[2023-10-11T05:00:15.814+0000] {process_utils.py:190} INFO -   Downloading scikit_learn-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
[2023-10-11T05:00:16.115+0000] {process_utils.py:190} INFO - Collecting numpy (from lightgbm==4.1.0->-r /tmp/venv4luzmjjv/requirements.txt (line 1))
[2023-10-11T05:00:16.116+0000] {process_utils.py:190} INFO -   Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/98/5d/5738903efe0ecb73e51eb44feafba32bdba2081263d40c5043568ff60faf/numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
[2023-10-11T05:00:16.180+0000] {process_utils.py:190} INFO -   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2023-10-11T05:00:16.351+0000] {process_utils.py:190} INFO - Collecting scipy (from lightgbm==4.1.0->-r /tmp/venv4luzmjjv/requirements.txt (line 1))
[2023-10-11T05:00:16.419+0000] {process_utils.py:190} INFO -   Downloading scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
[2023-10-11T05:00:21.350+0000] {process_utils.py:190} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 10.9 MB/s eta 0:00:00
[2023-10-11T05:00:21.509+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas==2.0.3->-r /tmp/venv4luzmjjv/requirements.txt (line 2))
[2023-10-11T05:00:21.565+0000] {process_utils.py:190} INFO -   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[2023-10-11T05:00:21.587+0000] {process_utils.py:190} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 12.1 MB/s eta 0:00:00
[2023-10-11T05:00:21.692+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas==2.0.3->-r /tmp/venv4luzmjjv/requirements.txt (line 2))
[2023-10-11T05:00:21.692+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
[2023-10-11T05:00:21.746+0000] {process_utils.py:190} INFO -   Downloading pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
[2023-10-11T05:00:21.799+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas==2.0.3->-r /tmp/venv4luzmjjv/requirements.txt (line 2))
[2023-10-11T05:00:21.868+0000] {process_utils.py:190} INFO -   Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
[2023-10-11T05:00:22.007+0000] {process_utils.py:190} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 2.4 MB/s eta 0:00:00
[2023-10-11T05:00:22.127+0000] {process_utils.py:190} INFO - Collecting joblib>=1.1.1 (from scikit-learn==1.3.1->-r /tmp/venv4luzmjjv/requirements.txt (line 3))
[2023-10-11T05:00:22.128+0000] {process_utils.py:190} INFO -   Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
[2023-10-11T05:00:22.192+0000] {process_utils.py:190} INFO -   Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
[2023-10-11T05:00:22.239+0000] {process_utils.py:190} INFO - Collecting threadpoolctl>=2.0.0 (from scikit-learn==1.3.1->-r /tmp/venv4luzmjjv/requirements.txt (line 3))
[2023-10-11T05:00:22.240+0000] {process_utils.py:190} INFO -   Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
[2023-10-11T05:00:22.303+0000] {process_utils.py:190} INFO -   Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
[2023-10-11T05:00:22.364+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.0.3->-r /tmp/venv4luzmjjv/requirements.txt (line 2))
[2023-10-11T05:00:22.446+0000] {process_utils.py:190} INFO -   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[2023-10-11T05:00:22.555+0000] {process_utils.py:190} INFO - Downloading lightgbm-4.1.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
[2023-10-11T05:00:22.939+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 8.0 MB/s eta 0:00:00
[2023-10-11T05:00:23.017+0000] {process_utils.py:190} INFO - Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2023-10-11T05:00:24.201+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 10.8 MB/s eta 0:00:00
[2023-10-11T05:00:24.250+0000] {process_utils.py:190} INFO - Downloading scikit_learn-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
[2023-10-11T05:00:25.604+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 8.0 MB/s eta 0:00:00
[2023-10-11T05:00:25.658+0000] {process_utils.py:190} INFO - Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
[2023-10-11T05:00:25.687+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 10.7 MB/s eta 0:00:00
[2023-10-11T05:00:25.736+0000] {process_utils.py:190} INFO - Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2023-10-11T05:00:27.432+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 9.6 MB/s eta 0:00:00
[2023-10-11T05:00:27.476+0000] {process_utils.py:190} INFO - Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
[2023-10-11T05:00:27.521+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.5/502.5 kB 11.1 MB/s eta 0:00:00
[2023-10-11T05:00:27.576+0000] {process_utils.py:190} INFO - Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
[2023-10-11T05:00:27.786+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas, lightgbm
[2023-10-11T05:00:34.370+0000] {process_utils.py:190} INFO - Successfully installed joblib-1.3.2 lightgbm-4.1.0 numpy-1.24.4 pandas-2.0.3 python-dateutil-2.8.2 pytz-2023.3.post1 scikit-learn-1.3.1 scipy-1.10.1 six-1.16.0 threadpoolctl-3.2.0 tzdata-2023.3
[2023-10-11T05:00:34.553+0000] {process_utils.py:190} INFO - 
[2023-10-11T05:00:34.554+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2 -> 23.2.1
[2023-10-11T05:00:34.554+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-10-11T05:00:34.938+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 602, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 439, in _execute_python_callable_in_subprocess
    python_callable_source=self.get_python_source(),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 274, in get_python_source
    raw_source = inspect.getsource(self.python_callable)
  File "/usr/local/lib/python3.8/inspect.py", line 997, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/lib/python3.8/inspect.py", line 979, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/lib/python3.8/inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
[2023-10-11T05:00:34.945+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=docker, task_id=virtualenv_python, execution_date=20231011T050010, start_date=20231011T050013, end_date=20231011T050034
[2023-10-11T05:00:34.953+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1426 for task virtualenv_python (could not get source code; 495)
[2023-10-11T05:00:34.984+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-11T05:00:34.994+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
